#!/bin/bash
shopt -s globstar nullglob nocaseglob
for file in **/*.gif; do if [[ -f "$file" ]]; then filename=$(echo "$file" | sed 's/\.[^.]*$//'); echo "$filename"; fi; done | sort -f -d | tr '\n' '\0' | xargs -0 -n1 echo && echo ""
