#!/usr/bin/env bash
# Install nginx

sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i 's/^.*listen\s*80.*/    listen 80;/g' /etc/nginx/sites-available/default
sudo service nginx restart
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
