#!/usr/bin/env bash
# Install nginx

sudo apt-get -y update
sudo apt-get install -y nginx
sudo sed -i 's/^\(listen\s*80\)/# \1/' /etc/nginx/sites-available/default
sudo sed -i 's/# \(listen\s*\[::\]:80\)/\1/' /etc/nginx/sites-available/default
sudo service nginx reload
echo "Hello World!" | sudo tee /var/www/html/index.html
