#!/usr/bin/env bash
# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup

sudo sed -i '/server_name _;/a \
\
    location /redirect_me { \
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \
    } \
' /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx restart
