#!/usr/bin/env bash
# Install nginx

sudo apt-get update
sudo apt-get -y install nginx

# Define the redirection configuration
REDIRECTION_CONFIG="\
    location /redirect_me { \\
        return 301 https://www.example.com/new_page; \\
    }"

# Use sed to replace the default configuration with the redirection configuration
sudo sed -i "/listen \[::\]:80 default_server;/a ${REDIRECTION_CONFIG}" /etc/nginx/sites-available/default

# Test Nginx configuration
sudo nginx -t

# Restart Nginx to apply changes
sudo systemctl restart nginx
