#!/usr/bin/env bash
# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Define the custom 404 page content
CUSTOM_404_PAGE="\
<!DOCTYPE html> \\
<html lang=\"en\"> \\
<head> \\
    <meta charset=\"UTF-8\"> \\
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"> \\
    <title>404 Not Found</title> \\
</head> \\
<body> \\
    <h1>404 Not Found</h1> \\
    <p>Ceci n'est pas une page</p> \\
</body> \\
</html>"

# Create a custom 404 page file
echo "${CUSTOM_404_PAGE}" | sudo tee /var/www/html/404.html > /dev/null

# Configure Nginx to use the custom 404 page
sudo sed -i '/server_name _;/a \ \ \ \ error_page 404 /404.html;' /etc/nginx/sites-available/default

# Test Nginx configuration
sudo nginx -t

# Restart Nginx to apply changes
sudo systemctl restart nginx
