#!/usr/bin/env bash
#a Bash script that displays the content of the file /etc/passwd.
#script should only display:username, user id, Home directory path for the user

while read -r password;
do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
    echo "--------------------"
done < "/etc/passwd"
