#!/usr/bin/env bash
#a Bash script that gives you information about the school file.


file_path="school"

if [ -e "$file_path" ]
then
    echo "$file_path file exists"

    if [ -s "$file_path" ]
    then
        echo "$file_path file is not empty"

        if [ -f "$file_path" ]
	then
            echo "$file_path is a regular file"
        else

            :
        fi
    else
        echo "$file_path file is empty"
    fi
else
    echo "$file_path file does not exist"
fi
